version: '3'

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx:1.25.1'
    ports:
      - '80:80'
    expose:
      - 80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'

  rust:
    container_name: 'rust'
    build: ./server
