version: '3'

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx:1.25.1'
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'

  frontend:
    container_name: 'angular'
    build: ./frontend
    ports:
      - '3000'
